// LanguageContext — stores the selected interface language and provides
// a t() translation function for UI strings and a system prompt injection string.
import React, { createContext, useContext, useState, useCallback, ReactNode } from 'react';

export type LangCode = 'fr' | 'en' | 'es' | 'de' | 'it' | 'pt' | 'zh' | 'ja' | 'ar';

// ── Translation dictionaries ──────────────────────────────────────────────────
const TRANSLATIONS: Record<LangCode, Record<string, string>> = {
  fr: {
    // Nav
    builder: 'Builder',
    workspaces: 'Workspaces',
    chat: 'Chat',
    profile: 'Profil',
    settings: 'Paramètres',
    // Common
    new: 'Nouveau',
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    close: 'Fermer',
    back: 'Retour',
    confirm: 'Confirmer',
    add: 'Ajouter',
    create: 'Créer',
    search: 'Rechercher',
    loading: 'Chargement...',
    // Chat
    newConversation: 'Nouvelle conversation',
    conversationHistory: 'Historique des conversations',
    typeMessage: 'Message ou /raccourci...',
    generating: 'Génération en cours...',
    clearConversation: 'Effacer la conversation ?',
    clearConversationMsg: 'Tous les messages seront supprimés.',
    sendMessage: 'Envoyer',
    // Workspaces
    workspace: 'Workspace',
    conversations: 'Conversations',
    modes: 'Compétences',
    tasks: 'Tâches',
    database: 'Base de données',
    activeWorkspace: 'Actif',
    newWorkspace: 'Nouveau workspace',
    deleteWorkspace: 'Supprimer ce workspace ?',
    deleteWorkspaceMsg: 'Ce workspace et toutes ses conversations seront supprimés.',
    // Profile
    account: 'Compte',
    aiMemory: 'Mémoire IA',
    identity: 'Identité',
    // Settings
    appearance: 'Apparence',
    darkTheme: 'Thème sombre',
    lightTheme: 'Thème clair',
    interfaceLanguage: 'Langue de l\'interface',
    apiKey: 'Clé API',
    llmModel: 'Modèle LLM',
    generationParams: 'Paramètres de génération',
    systemPrompt: 'Prompt système',
    webSearch: 'Moteur de recherche web',
    // Database
    insertFile: 'Insérer',
    sortBy: 'Trier :',
    noFiles: 'Aucun fichier',
    folders: 'Dossiers',
    subFolders: 'Sous-dossiers',
    rootFiles: 'Fichiers racine',
    files: 'Fichiers',
    newFolder: 'Nouveau dossier',
    newSubFolder: 'Nouveau sous-dossier',
    fileContent: 'Contenu du fichier',
    rename: 'Renommer',
    renameWorkspace: 'Renommer le workspace',
  },
  en: {
    builder: 'Builder',
    workspaces: 'Workspaces',
    chat: 'Chat',
    profile: 'Profile',
    settings: 'Settings',
    new: 'New',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    back: 'Back',
    confirm: 'Confirm',
    add: 'Add',
    create: 'Create',
    search: 'Search',
    loading: 'Loading...',
    newConversation: 'New conversation',
    conversationHistory: 'Conversation history',
    typeMessage: 'Message or /shortcut...',
    generating: 'Generating...',
    clearConversation: 'Clear conversation?',
    clearConversationMsg: 'All messages will be deleted.',
    sendMessage: 'Send',
    workspace: 'Workspace',
    conversations: 'Conversations',
    modes: 'Skills',
    tasks: 'Tasks',
    database: 'Database',
    activeWorkspace: 'Active',
    newWorkspace: 'New workspace',
    deleteWorkspace: 'Delete this workspace?',
    deleteWorkspaceMsg: 'This workspace and all its conversations will be deleted.',
    account: 'Account',
    aiMemory: 'AI Memory',
    identity: 'Identity',
    appearance: 'Appearance',
    darkTheme: 'Dark theme',
    lightTheme: 'Light theme',
    interfaceLanguage: 'Interface language',
    apiKey: 'API Key',
    llmModel: 'LLM Model',
    generationParams: 'Generation parameters',
    systemPrompt: 'System prompt',
    webSearch: 'Web search engine',
    insertFile: 'Insert',
    sortBy: 'Sort:',
    noFiles: 'No files',
    folders: 'Folders',
    subFolders: 'Sub-folders',
    rootFiles: 'Root files',
    files: 'Files',
    newFolder: 'New folder',
    newSubFolder: 'New sub-folder',
    fileContent: 'File content',
    rename: 'Rename',
    renameWorkspace: 'Rename workspace',
  },
  es: {
    builder: 'Constructor',
    workspaces: 'Espacios de trabajo',
    chat: 'Chat',
    profile: 'Perfil',
    settings: 'Ajustes',
    new: 'Nuevo',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    close: 'Cerrar',
    back: 'Volver',
    confirm: 'Confirmar',
    add: 'Añadir',
    create: 'Crear',
    search: 'Buscar',
    loading: 'Cargando...',
    newConversation: 'Nueva conversación',
    conversationHistory: 'Historial de conversaciones',
    typeMessage: 'Mensaje o /atajo...',
    generating: 'Generando...',
    clearConversation: '¿Borrar conversación?',
    clearConversationMsg: 'Todos los mensajes serán eliminados.',
    sendMessage: 'Enviar',
    workspace: 'Espacio de trabajo',
    conversations: 'Conversaciones',
    modes: 'Competencias',
    tasks: 'Tareas',
    database: 'Base de datos',
    activeWorkspace: 'Activo',
    newWorkspace: 'Nuevo espacio de trabajo',
    deleteWorkspace: '¿Eliminar este espacio?',
    deleteWorkspaceMsg: 'Este espacio y todas sus conversaciones serán eliminados.',
    account: 'Cuenta',
    aiMemory: 'Memoria IA',
    identity: 'Identidad',
    appearance: 'Apariencia',
    darkTheme: 'Tema oscuro',
    lightTheme: 'Tema claro',
    interfaceLanguage: 'Idioma de la interfaz',
    apiKey: 'Clave API',
    llmModel: 'Modelo LLM',
    generationParams: 'Parámetros de generación',
    systemPrompt: 'Indicación del sistema',
    webSearch: 'Motor de búsqueda web',
    insertFile: 'Insertar',
    sortBy: 'Ordenar:',
    noFiles: 'Sin archivos',
    folders: 'Carpetas',
    subFolders: 'Subcarpetas',
    rootFiles: 'Archivos raíz',
    files: 'Archivos',
    newFolder: 'Nueva carpeta',
    newSubFolder: 'Nueva subcarpeta',
    fileContent: 'Contenido del archivo',
    rename: 'Renombrar',
    renameWorkspace: 'Renombrar espacio de trabajo',
  },
  de: {
    builder: 'Builder',
    workspaces: 'Arbeitsbereiche',
    chat: 'Chat',
    profile: 'Profil',
    settings: 'Einstellungen',
    new: 'Neu',
    save: 'Speichern',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    close: 'Schließen',
    back: 'Zurück',
    confirm: 'Bestätigen',
    add: 'Hinzufügen',
    create: 'Erstellen',
    search: 'Suchen',
    loading: 'Laden...',
    newConversation: 'Neue Unterhaltung',
    conversationHistory: 'Gesprächsverlauf',
    typeMessage: 'Nachricht oder /Kürzel...',
    generating: 'Wird generiert...',
    clearConversation: 'Gespräch löschen?',
    clearConversationMsg: 'Alle Nachrichten werden gelöscht.',
    sendMessage: 'Senden',
    workspace: 'Arbeitsbereich',
    conversations: 'Gespräche',
    modes: 'Fähigkeiten',
    tasks: 'Aufgaben',
    database: 'Datenbank',
    activeWorkspace: 'Aktiv',
    newWorkspace: 'Neuer Arbeitsbereich',
    deleteWorkspace: 'Diesen Bereich löschen?',
    deleteWorkspaceMsg: 'Dieser Bereich und alle Gespräche werden gelöscht.',
    account: 'Konto',
    aiMemory: 'KI-Gedächtnis',
    identity: 'Identität',
    appearance: 'Erscheinungsbild',
    darkTheme: 'Dunkles Thema',
    lightTheme: 'Helles Thema',
    interfaceLanguage: 'Oberflächensprache',
    apiKey: 'API-Schlüssel',
    llmModel: 'LLM-Modell',
    generationParams: 'Generierungsparameter',
    systemPrompt: 'System-Prompt',
    webSearch: 'Websuchmaschine',
    insertFile: 'Einfügen',
    sortBy: 'Sortieren:',
    noFiles: 'Keine Dateien',
    folders: 'Ordner',
    subFolders: 'Unterordner',
    rootFiles: 'Wurzeldateien',
    files: 'Dateien',
    newFolder: 'Neuer Ordner',
    newSubFolder: 'Neuer Unterordner',
    fileContent: 'Dateiinhalt',
    rename: 'Umbenennen',
    renameWorkspace: 'Arbeitsbereich umbenennen',
  },
  it: {
    builder: 'Costruttore',
    workspaces: 'Spazi di lavoro',
    chat: 'Chat',
    profile: 'Profilo',
    settings: 'Impostazioni',
    new: 'Nuovo',
    save: 'Salva',
    cancel: 'Annulla',
    delete: 'Elimina',
    edit: 'Modifica',
    close: 'Chiudi',
    back: 'Indietro',
    confirm: 'Conferma',
    add: 'Aggiungi',
    create: 'Crea',
    search: 'Cerca',
    loading: 'Caricamento...',
    newConversation: 'Nuova conversazione',
    conversationHistory: 'Cronologia conversazioni',
    typeMessage: 'Messaggio o /scorciatoia...',
    generating: 'Generazione in corso...',
    clearConversation: 'Cancellare la conversazione?',
    clearConversationMsg: 'Tutti i messaggi saranno eliminati.',
    sendMessage: 'Invia',
    workspace: 'Spazio di lavoro',
    conversations: 'Conversazioni',
    modes: 'Competenze',
    tasks: 'Attività',
    database: 'Database',
    activeWorkspace: 'Attivo',
    newWorkspace: 'Nuovo spazio di lavoro',
    deleteWorkspace: 'Eliminare questo spazio?',
    deleteWorkspaceMsg: 'Questo spazio e tutte le sue conversazioni saranno eliminati.',
    account: 'Account',
    aiMemory: 'Memoria IA',
    identity: 'Identità',
    appearance: 'Aspetto',
    darkTheme: 'Tema scuro',
    lightTheme: 'Tema chiaro',
    interfaceLanguage: 'Lingua dell\'interfaccia',
    apiKey: 'Chiave API',
    llmModel: 'Modello LLM',
    generationParams: 'Parametri di generazione',
    systemPrompt: 'Prompt di sistema',
    webSearch: 'Motore di ricerca web',
    insertFile: 'Inserisci',
    sortBy: 'Ordina:',
    noFiles: 'Nessun file',
    folders: 'Cartelle',
    subFolders: 'Sottocartelle',
    rootFiles: 'File radice',
    files: 'File',
    newFolder: 'Nuova cartella',
    newSubFolder: 'Nuova sottocartella',
    fileContent: 'Contenuto del file',
    rename: 'Rinomina',
    renameWorkspace: 'Rinomina spazio di lavoro',
  },
  pt: {
    builder: 'Construtor',
    workspaces: 'Espaços de trabalho',
    chat: 'Chat',
    profile: 'Perfil',
    settings: 'Configurações',
    new: 'Novo',
    save: 'Salvar',
    cancel: 'Cancelar',
    delete: 'Excluir',
    edit: 'Editar',
    close: 'Fechar',
    back: 'Voltar',
    confirm: 'Confirmar',
    add: 'Adicionar',
    create: 'Criar',
    search: 'Pesquisar',
    loading: 'Carregando...',
    newConversation: 'Nova conversa',
    conversationHistory: 'Histórico de conversas',
    typeMessage: 'Mensagem ou /atalho...',
    generating: 'Gerando...',
    clearConversation: 'Limpar conversa?',
    clearConversationMsg: 'Todas as mensagens serão excluídas.',
    sendMessage: 'Enviar',
    workspace: 'Espaço de trabalho',
    conversations: 'Conversas',
    modes: 'Competências',
    tasks: 'Tarefas',
    database: 'Banco de dados',
    activeWorkspace: 'Ativo',
    newWorkspace: 'Novo espaço de trabalho',
    deleteWorkspace: 'Excluir este espaço?',
    deleteWorkspaceMsg: 'Este espaço e todas as suas conversas serão excluídos.',
    account: 'Conta',
    aiMemory: 'Memória IA',
    identity: 'Identidade',
    appearance: 'Aparência',
    darkTheme: 'Tema escuro',
    lightTheme: 'Tema claro',
    interfaceLanguage: 'Idioma da interface',
    apiKey: 'Chave API',
    llmModel: 'Modelo LLM',
    generationParams: 'Parâmetros de geração',
    systemPrompt: 'Prompt do sistema',
    webSearch: 'Motor de busca web',
    insertFile: 'Inserir',
    sortBy: 'Ordenar:',
    noFiles: 'Nenhum arquivo',
    folders: 'Pastas',
    subFolders: 'Subpastas',
    rootFiles: 'Arquivos raiz',
    files: 'Arquivos',
    newFolder: 'Nova pasta',
    newSubFolder: 'Nova subpasta',
    fileContent: 'Conteúdo do arquivo',
    rename: 'Renomear',
    renameWorkspace: 'Renomear espaço de trabalho',
  },
  zh: {
    builder: '构建器',
    workspaces: '工作空间',
    chat: '对话',
    profile: '个人资料',
    settings: '设置',
    new: '新建',
    save: '保存',
    cancel: '取消',
    delete: '删除',
    edit: '编辑',
    close: '关闭',
    back: '返回',
    confirm: '确认',
    add: '添加',
    create: '创建',
    search: '搜索',
    loading: '加载中...',
    newConversation: '新对话',
    conversationHistory: '对话历史',
    typeMessage: '消息或/快捷方式...',
    generating: '生成中...',
    clearConversation: '清除对话？',
    clearConversationMsg: '所有消息将被删除。',
    sendMessage: '发送',
    workspace: '工作空间',
    conversations: '对话',
    modes: '技能',
    tasks: '任务',
    database: '数据库',
    activeWorkspace: '活跃',
    newWorkspace: '新工作空间',
    deleteWorkspace: '删除此工作空间？',
    deleteWorkspaceMsg: '此工作空间及其所有对话将被删除。',
    account: '账户',
    aiMemory: 'AI记忆',
    identity: '身份',
    appearance: '外观',
    darkTheme: '深色主题',
    lightTheme: '浅色主题',
    interfaceLanguage: '界面语言',
    apiKey: 'API密钥',
    llmModel: 'LLM模型',
    generationParams: '生成参数',
    systemPrompt: '系统提示',
    webSearch: '网页搜索引擎',
    insertFile: '插入',
    sortBy: '排序:',
    noFiles: '没有文件',
    folders: '文件夹',
    subFolders: '子文件夹',
    rootFiles: '根目录文件',
    files: '文件',
    newFolder: '新建文件夹',
    newSubFolder: '新建子文件夹',
    fileContent: '文件内容',
    rename: '重命名',
    renameWorkspace: '重命名工作空间',
  },
  ja: {
    builder: 'ビルダー',
    workspaces: 'ワークスペース',
    chat: 'チャット',
    profile: 'プロフィール',
    settings: '設定',
    new: '新規',
    save: '保存',
    cancel: 'キャンセル',
    delete: '削除',
    edit: '編集',
    close: '閉じる',
    back: '戻る',
    confirm: '確認',
    add: '追加',
    create: '作成',
    search: '検索',
    loading: '読込中...',
    newConversation: '新しい会話',
    conversationHistory: '会話履歴',
    typeMessage: 'メッセージまたは/ショートカット...',
    generating: '生成中...',
    clearConversation: '会話をクリアしますか？',
    clearConversationMsg: 'すべてのメッセージが削除されます。',
    sendMessage: '送信',
    workspace: 'ワークスペース',
    conversations: '会話',
    modes: 'スキル',
    tasks: 'タスク',
    database: 'データベース',
    activeWorkspace: 'アクティブ',
    newWorkspace: '新しいワークスペース',
    deleteWorkspace: 'このワークスペースを削除しますか？',
    deleteWorkspaceMsg: 'このワークスペースとすべての会話が削除されます。',
    account: 'アカウント',
    aiMemory: 'AIメモリ',
    identity: 'アイデンティティ',
    appearance: '外観',
    darkTheme: 'ダークテーマ',
    lightTheme: 'ライトテーマ',
    interfaceLanguage: 'インターフェース言語',
    apiKey: 'APIキー',
    llmModel: 'LLMモデル',
    generationParams: '生成パラメータ',
    systemPrompt: 'システムプロンプト',
    webSearch: 'ウェブ検索エンジン',
    insertFile: '挿入',
    sortBy: '並べ替え:',
    noFiles: 'ファイルなし',
    folders: 'フォルダ',
    subFolders: 'サブフォルダ',
    rootFiles: 'ルートファイル',
    files: 'ファイル',
    newFolder: '新しいフォルダ',
    newSubFolder: '新しいサブフォルダ',
    fileContent: 'ファイル内容',
    rename: '名前の変更',
    renameWorkspace: 'ワークスペースの名前変更',
  },
  ar: {
    builder: 'المنشئ',
    workspaces: 'مساحات العمل',
    chat: 'دردشة',
    profile: 'الملف الشخصي',
    settings: 'الإعدادات',
    new: 'جديد',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    close: 'إغلاق',
    back: 'رجوع',
    confirm: 'تأكيد',
    add: 'إضافة',
    create: 'إنشاء',
    search: 'بحث',
    loading: 'جار التحميل...',
    newConversation: 'محادثة جديدة',
    conversationHistory: 'سجل المحادثات',
    typeMessage: 'رسالة أو /اختصار...',
    generating: 'جار التوليد...',
    clearConversation: 'مسح المحادثة؟',
    clearConversationMsg: 'سيتم حذف جميع الرسائل.',
    sendMessage: 'إرسال',
    workspace: 'مساحة العمل',
    conversations: 'المحادثات',
    modes: 'المهارات',
    tasks: 'المهام',
    database: 'قاعدة البيانات',
    activeWorkspace: 'نشط',
    newWorkspace: 'مساحة عمل جديدة',
    deleteWorkspace: 'حذف هذه المساحة؟',
    deleteWorkspaceMsg: 'ستُحذف هذه المساحة وجميع محادثاتها.',
    account: 'الحساب',
    aiMemory: 'ذاكرة الذكاء الاصطناعي',
    identity: 'الهوية',
    appearance: 'المظهر',
    darkTheme: 'السمة الداكنة',
    lightTheme: 'السمة الفاتحة',
    interfaceLanguage: 'لغة الواجهة',
    apiKey: 'مفتاح API',
    llmModel: 'نموذج LLM',
    generationParams: 'معاملات التوليد',
    systemPrompt: 'موجه النظام',
    webSearch: 'محرك البحث على الويب',
    insertFile: 'إدراج',
    sortBy: 'ترتيب:',
    noFiles: 'لا توجد ملفات',
    folders: 'المجلدات',
    subFolders: 'المجلدات الفرعية',
    rootFiles: 'ملفات الجذر',
    files: 'الملفات',
    newFolder: 'مجلد جديد',
    newSubFolder: 'مجلد فرعي جديد',
    fileContent: 'محتوى الملف',
    rename: 'إعادة تسمية',
    renameWorkspace: 'إعادة تسمية مساحة العمل',
  },
};

// System prompt injection text per language
export const LANG_SYSTEM_INJECTION: Record<LangCode, string> = {
  fr: 'IMPORTANT: Réponds TOUJOURS en français, quelle que soit la langue de la question.',
  en: 'IMPORTANT: ALWAYS respond in English, regardless of the language of the question.',
  es: 'IMPORTANTE: Responde SIEMPRE en español, independientemente del idioma de la pregunta.',
  de: 'WICHTIG: Antworte IMMER auf Deutsch, unabhängig von der Sprache der Frage.',
  it: 'IMPORTANTE: Rispondi SEMPRE in italiano, indipendentemente dalla lingua della domanda.',
  pt: 'IMPORTANTE: Responda SEMPRE em português, independentemente do idioma da pergunta.',
  zh: '重要：无论问题用何种语言，请始终用中文回答。',
  ja: '重要：質問の言語に関係なく、常に日本語で回答してください。',
  ar: 'مهم: أجب دائماً باللغة العربية، بغض النظر عن لغة السؤال.',
};

// ── Context ───────────────────────────────────────────────────────────────────
interface LanguageContextType {
  lang: LangCode;
  setLang: (lang: LangCode) => void;
  t: (key: string, fallback?: string) => string;
  systemInjection: string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<LangCode>('fr');

  const setLang = useCallback((l: LangCode) => setLangState(l), []);

  const t = useCallback((key: string, fallback?: string): string => {
    return TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS['fr']?.[key] ?? fallback ?? key;
  }, [lang]);

  const systemInjection = LANG_SYSTEM_INJECTION[lang];

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, systemInjection }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
